#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-em-http-request
Version  : 1.1.4
Release  : 7
URL      : https://rubygems.org/downloads/em-http-request-1.1.4.gem
Source0  : https://rubygems.org/downloads/em-http-request-1.1.4.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-addressable
BuildRequires : rubygem-bundler
BuildRequires : rubygem-cookiejar
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-em-socksify
BuildRequires : rubygem-eventmachine
BuildRequires : rubygem-multi_json
BuildRequires : rubygem-rack
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support

%description
# EM-HTTP-Request
[![Gem Version](https://badge.fury.io/rb/em-http-request.png)](http://rubygems.org/gems/em-http-request) [![Build Status](https://travis-ci.org/igrigorik/em-http-request.svg)](https://travis-ci.org/igrigorik/em-http-request)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n em-http-request-1.1.4
gem spec %{SOURCE0} -l --ruby > rubygem-em-http-request.gemspec

%build
gem build rubygem-em-http-request.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
em-http-request-1.1.4.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/em-http-request-1.1.4.gem
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/.gemtest
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/.rspec
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/Changelog.md
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/README.md
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/benchmarks/clients.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/benchmarks/em-excon.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/benchmarks/em-profile.gif
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/benchmarks/em-profile.txt
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/benchmarks/server.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/em-http-request.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/examples/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/examples/digest_auth/client.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/examples/digest_auth/server.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/examples/fetch.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/examples/fibered-http.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/examples/multi.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/examples/oauth-tweet.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/examples/socks5.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/lib/em-http-request.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/lib/em-http.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/lib/em-http/client.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/lib/em-http/core_ext/bytesize.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/lib/em-http/decoders.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/lib/em-http/http_client_options.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/lib/em-http/http_connection.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/lib/em-http/http_connection_options.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/lib/em-http/http_encoding.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/lib/em-http/http_header.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/lib/em-http/http_status_codes.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/lib/em-http/middleware/digest_auth.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/lib/em-http/middleware/json_response.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/lib/em-http/middleware/oauth.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/lib/em-http/middleware/oauth2.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/lib/em-http/multi.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/lib/em-http/request.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/lib/em-http/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/spec/client_fiber_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/spec/client_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/spec/digest_auth_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/spec/dns_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/spec/encoding_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/spec/external_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/spec/fixtures/google.ca
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/spec/fixtures/gzip-sample.gz
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/spec/gzip_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/spec/helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/spec/http_proxy_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/spec/middleware/oauth2_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/spec/middleware_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/spec/multi_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/spec/pipelining_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/spec/redirect_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/spec/socksify_proxy_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/spec/ssl_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/spec/stallion.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-http-request-1.1.4/spec/stub_server.rb
/usr/lib64/ruby/gems/2.3.0/specifications/em-http-request-1.1.4.gemspec
